import React from 'react';
import Layout from '../../shared/layout';

const Terms = () => {
    return ( 
        <Layout>
            <div>
                <h3 className="playfair" style={{marginTop: '50px', marginBottom: '30px', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>Terms of Use</h3>
                <p className="montserrat" style={{marginLeft: '150px', marginRight: '150px', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>Welcome to the Yerbaropa website, yerbaropa.com owned and operated by Yerbaropa, LLC. Except as otherwise noted herein, these terms and conditions (the "Terms") govern your use of the Yerbaropa Website and Yerbaropa services, applications, content and products (collectively, the "Site"). Please read the following terms and conditions of use, because your use of the Site constitutes your agreement to follow and be bound by these Terms. If you do not agree to these Terms, you should not access or use the Site. Yerbaropa reserves the right to make changes to the Site and to these Terms from time to time. When we make changes, we will post them here. For this reason, we encourage you to review these Terms whenever you use our Site because by visiting the Site, you agree to accept any such changes. Yerbaropa provides you with access to and use of the Site subject to your compliance with the Terms. No material from the Site may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, except as specifically permitted on the Site. The Site, including all of its information and content, such as text, data, wallpaper, icons, characters, artwork, images, photographs, graphics, music, sound, messages, software and the HTML used to generate the pages (collectively, "Materials and Content"), is Yerbaropa property or that of our suppliers or licensors and is protected by patent, trademark and/or copyright under United States and/or foreign laws. Except as otherwise provided on the site or in these Terms, you may not use, download, upload, copy, print, display, perform, reproduce, publish, modify, delete, add to, license, post, transmit or distribute any Materials and Content from this Site in whole or in part, for any public or commercial purpose without the specific prior written permission of Yerbaropa. We grant you a personal, limited, nonexclusive, nontransferable license to access the Site and to use the information and services contained here solely for your personal, noncommercial use as described below. We reserve the right, for any reason or for no reason, in our sole discretion and without notice to you, to revise the products and services described on the Site and to terminate, change, suspend or discontinue any aspect of the Site, including, but not limited to, the Materials and Content on the Site as well as features and/or hours of availability of the Site, and we will not be liable to you or to any third party for doing so. We may also impose rules for and limits on use of the Site or restrict your access to part, or all, of the Site without notice or penalty. We have the right to change these rules and/or limitations at any time, in our sole discretion.</p>

                <h3 className="playfair" style={{marginTop: '30px', marginBottom: '30px', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>Security Rules</h3>
                <p className="montserrat" style={{marginLeft: '150px', marginRight: '150px', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>Violations of system or network security may result in civil or criminal liability. Yerbaropa investigates violations and may involve, and cooperate with, law enforcement authorities in prosecuting any user or users who are involved in such violations. You are prohibited from violating or attempting to violate the security of the Site, including, without limitation, the following: 
                    Accessing data not intended for you or logging on to a Yerbaropa server or account that you are not authorized to access
                    Attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization (or succeeding in such an attempt)
                    Attempting to interfere or interfering with the operation of our Site, our provision of services to any other visitors to our Site and our hosting provider or our network, including, without limitation, via means of submitting a virus to the Site, overloading, “flooding,” “email bombing” or “crashing” the Site
                    Forging any TCP/IP packet header or any part of the header information in any email or transmission or posting to our Site
                </p>

                <h3 className="playfair" style={{marginTop: '30px', marginBottom: '30px', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>Disclaimers and Limitation of Liability</h3>
                <p className="montserrat" style={{marginLeft: '150px', marginRight: '150px', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>Yerbaropa publishes information on its Site as a convenience to its visitors. While Yerbaropa attempts to provide accurate and timely information, there may be inadvertent technical or factual inaccuracies and typographical errors. We reserve the right to make corrections and changes to the Site at any time without notice. The Yerbaropa products described on the Site may not be available in your region. Yerbaropa does not claim that the information on the Site is appropriate to your jurisdiction or that the products described on its Site will be available for purchase in all jurisdictions.</p>
            </div>
        </Layout>
     );
}
 
export default Terms;